/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */
plugins {
    alias(ag.plugins.docker.api) apply false
    alias(ag.plugins.nodejs) apply false
    alias(ag.plugins.release.github) apply false
    alias(ag.plugins.buildkonfig) apply false
    alias(ag.plugins.spring.boot) apply false
    alias(ag.plugins.spring.deps) apply false
    alias(ag.plugins.kotlin.plugin.multiplatform) apply false
    alias(ag.plugins.kotlin.plugin.jvm) apply false
    alias(ag.plugins.kotlin.plugin.serialization) apply false
    alias(ag.plugins.kotlin.plugin.spring) apply false
}

group = "io.github.sgpublic"
version = "1.0.0-beta02"
