/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
import com.github.gradle.node.pnpm.task.PnpmTask

plugins {
    alias(ag.plugins.nodejs)
}

node {
    download = true
    version = "18.20.1"
    nodeProjectDir = projectDir
}

tasks.register<PnpmTask>("runBuild") {
    dependsOn("pnpmInstall")
    args = listOf("run", "build")
}
